### PR TITLE
First class DeepLinks

### PR DESCRIPTION
**Pull request by leoiacovini**
This PR unifies the notion of route names and DeepLinks under just DeepLinks. This allows for an easier mental model of the app routing and enables us to deliver some requested features.

With those changes we now are able to:
- Make dynamic DeepLink navigation inside a nested flow
- Have prefix DeepLinks, allowing for Deep navigation into nested flows

In addition to that, we added some helpers to use a dynamic API instead of the code generated one, this should serve as some syntax sugar for common use case scenarios.

Sadly to support this, some breaking changes were made, we expect the migration to mostly smooth if you are not relying on the internals of the library, and most changes are related to providing DeepLink to every route, given that now this is required, and to do some renaming.

### CODE REVIEW

**Comment by simon-twonary** [comment]
Hi, I need this feature. Is this feature going to be released any time soon? 
Thank you!

**Comment by leoiacovini** [comment]
Hi @stwonary !
We put this change a bit on hold because we wanted to check how to make the less breaking possible, and also moving forward in a way that makes sense with the upcoming Navigator 2.0 changes planned for Flutter.

I will check with the team during this week how we can follow up with this PR :)

**Comment by stwonary** [comment]
Thanks for the fast response. Will try to use some workaround for the moment.

**Comment by leoiacovini** [comment]
Closing in favor of the NEXT API PR

**Pull request closed without merging**
