### PR TITLE
Updates code to flutter-1.17

### PR DESCRIPTION
**Pull request by williamhjcho**
There were some breaking changes regarding navigation, take a look here:
- https://flutter.dev/docs/release/breaking-changes/route-navigator-refactoring

Complementary doc: https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit#heading=h.l6kdsrb6j9id

- [x] everything seems to be in order, need a bump on this PR

### CODE REVIEW

**Comment by leoiacovini** [comment]
I think this closes https://github.com/nubank/nuvigator/issues/25

**Comment by williamhjcho** [comment]
Should I add the changelog here or on another PR?

**Comment by leoiacovini** [comment]
I think we can add the bump and changelog in this same PR, then after merging, I can make a release for us :)

**Comment by williamhjcho** [comment]
I'll leave the merging to you 👍 . 
Once a new version is released, I'll update the monorepo to point at it

**Comment by leoiacovini** [comment]
@williamhjcho Released!

**Pull request merged**
